const config ={
    name: "mkRComponent",
    description: "User Config file for mkRComponent. Contains the parameters and settings for the automated mkRComponent. This file is self generated by the mkRComponent init() function",
    // User Settings
    prefWritting:"jsx/tsx",
    prefLazy:"true/false",
    prefStyle:"css/sass",
    prefStory:"crf/mdx/both",
    useJSDocs: "true/false",
    incImgDir:"true/false",
    // Set Path for directories
    directories:{
        component:"./src/Components",
        layout:"./src/Layouts",
        Pages:"./src/Pages",
    }
}
export default config